CREATE TABLE NICKNAME
(
    NICKNAME_ID   RAW(16)                             NOT NULL,
    NICKNAME_1    VARCHAR2(255)                       NOT NULL,
    NICKNAME_2    VARCHAR2(255)                       NOT NULL,
    CREATE_USER   VARCHAR(32)                         NOT NULL,
    CREATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER   VARCHAR(32)                         NOT NULL,
    UPDATE_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT NICKNAME_ID_PK PRIMARY KEY (NICKNAME_ID)
);

CREATE INDEX NICKNAME_NICKNAME_1_IDX ON NICKNAME (NICKNAME_1);
CREATE INDEX NICKNAME_NICKNAME_2_IDX ON NICKNAME (NICKNAME_2);

CREATE TABLE FOREIGN_SURNAME
(
    FOREIGN_SURNAME_ID  RAW(16)                          NOT NULL,
    SURNAME          VARCHAR2(255)                       NOT NULL,
    ANCESTRY         VARCHAR2(255)                       NOT NULL,
    EFFECTIVE_DATE   TIMESTAMP                           NOT NULL,
    EXPIRY_DATE      TIMESTAMP                           NOT NULL,
    CREATE_USER      VARCHAR(32)                         NOT NULL,
    CREATE_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER      VARCHAR(32)                         NOT NULL,
    UPDATE_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FOREIGN_SURNAME_ID_PK PRIMARY KEY (FOREIGN_SURNAME_ID)
);

CREATE INDEX FOREIGN_SURNAME_SEARCH_IDX ON FOREIGN_SURNAME (SURNAME, ANCESTRY, EFFECTIVE_DATE, EXPIRY_DATE);

CREATE TABLE FREQUENCY_SURNAME
(
    FREQUENCY_SURNAME_ID   RAW(16)                             NOT NULL,
    SURNAME                VARCHAR2(255)                       NOT NULL,
    SURNAME_FREQUENCY      VARCHAR2(4000)                      NOT NULL,
    CREATE_USER            VARCHAR(32)                         NOT NULL,
    CREATE_DATE            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER            VARCHAR(32)                         NOT NULL,
    UPDATE_DATE            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FREQUENCY_SURNAME_ID_PK PRIMARY KEY (FREQUENCY_SURNAME_ID)
);

CREATE INDEX FREQUENCY_SURNAME_SURNAME_IDX ON FREQUENCY_SURNAME (SURNAME);
