GRANT SELECT ON "flyway_schema_history" TO PEN_READONLY;
GRANT SELECT ON MATCH_REASON_CODE TO PEN_READONLY;
GRANT SELECT ON PEN_MATCH_EVENT TO PEN_READONLY;
GRANT SELECT ON PEN_MATCH_SHEDLOCK TO PEN_READONLY;
GRANT SELECT ON POSSIBLE_MATCH TO PEN_READONLY;
