CREATE OR REPLACE EDITIONABLE SYNONYM PEN_DEMOG FOR "PEN_DEMOG"@"PENLINK.WORLD";
CREATE OR REPLACE EDITIONABLE SYNONYM NICKNAMES FOR "NICKNAMES"@"PENLINK.WORLD";
CREATE OR REPLACE EDITIONABLE SYNONYM SURNAME_FREQUENCY FOR "SURNAME_FREQUENCY"@"PENLINK.WORLD";