INSERT INTO MATCH_REASON_CODE (MATCH_REASON_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE,
                               CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('MINISTRY', 'Ministry Identified', 'Identified by Ministry', 8, to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/MINYANG', to_date('2020-08-14', 'YYYY-MM-DD'), 'IDIR/MINYANG',
        to_date('2019-08-14', 'YYYY-MM-DD'));

UPDATE POSSIBLE_MATCH
SET MATCH_REASON_CODE = 'MINISTRY'
WHERE MATCH_REASON_CODE = 'MI';

delete from MATCH_REASON_CODE
WHERE MATCH_REASON_CODE = 'MI';
