GRANT SELECT ON FLYWAY_SCHEMA_HISTORY TO PEN_READONLY;
GRANT SELECT ON MATCH_REASON_CODE TO PEN_READONLY;
GRANT SELECT ON PEN_MATCH_EVENT TO PEN_READONLY;
GRANT SELECT ON PEN_MATCH_SHEDLOCK TO PEN_READONLY;
GRANT SELECT ON POSSIBLE_MATCH TO PEN_READONLY;
